### ISSUE TITLE
Overflow in certain screen size.

### ISSUE THREAD

**Issue by Nandakishore-Menon** [Nandakishore-Menon/Student_Database_Management#1]
The UI is not responsive for a small subset of screen size. Need to fix this.

**Comment by GeoBrodas** [comment]
Could you add the label to repository too?

**Comment by GeoBrodas** [comment]
Ok cool ! Working on your issue will do by evening!

**Comment by GeoBrodas** [comment]
Do you want the same UI the sliding one?  Or a improvised one?
Like making it a simple plain format with no sliding??

**Comment by Nandakishore-Menon** [comment]
Thank you for your contribution!
